### ISSUE TITLE
'Monitor' object has no attribute '_popen'

### ISSUE THREAD

**Issue by AndrewBezold** [nheijmans/malzoo#10]
I'm getting this error when trying to use the 'monitor directory' feature.  From some minor debugging, it appears that it happens at the 'monitor.daemon=True' line (malzoo.py line 99 in the current master).  The other methods seem to use Process in this section rather than the object itself - perhaps this needs to be done for directory monitoring as well?

**Comment by nheijmans** [comment]
thanks for raising! I will dive into this over the weekend, try to replay it and come up with a fix

**Comment by AndrewBezold** [comment]
I did change it to use Process locally, and it appears to work.  It may really be just that simple.

**Comment by nheijmans** [comment]
Nice, could you provide a pull request?

**Comment by nheijmans** [comment]
applied a fix in 3c2dfdd
