### ISSUE TITLE
POP3 Instead of IMAP - Feature Request

### ISSUE THREAD

**Issue by Jantzs76** [nheijmans/malzoo#4]
Are we able to use POP3 instead of IMAP for the connection to the Exchange Mailbox? Or, can we specify the IMAP connection must be Secured IMAP? From looking at the configuration file, it doesn't look like either option is available.

**Comment by nheijmans** [comment]
Hi Jantzs76,

The IMAP supplier is connecting over a secure connection (IMAP4_SSL(hostname)) by default to the defined hostname of the configuration file. POP3 is not implemented but will be added to the backlog. Thank you for your feedback!

**Comment by nheijmans** [comment]
Closing this issue as POP3 has not been requested since this issue and Malzoo is migrated to python3 it requires review
