### ISSUE TITLE
Sample processing argument mismatch

### ISSUE THREAD

**Issue by tcwaddell** [nheijmans/malzoo#7]
Malzoo produces the following error when attempting to process an email with no attachment.

> root@ubuntu:/opt/malzoo# python malzoo.py 
[*] Malzoo runs in monitor mode now!
[*] Starting components...
[+] Starting API supplier!
[+] Starting mail supplier!
Process EmailWorker-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/malzoo/malzoo/common/abstract.py", line 62, in run
    self.process(sample)
TypeError: process() takes exactly 3 arguments (2 given)

**Comment by nheijmans** [comment]
Hi tcwaddell,

Thanks, the issue seems to be in the emailworker.py where a tag is required in the process function. In 33e6b13 commit I have added a quick fix so Malzoo is app is working again. I will look for a more sustainable solution later this week. I will keep this issue open till then.
