### ISSUE TITLE
Splunk port configuration ignored

### ISSUE THREAD

**Issue by tcwaddell** [nheijmans/malzoo#8]
Malzoo does not use the Splunk port specified in the configuration file. It is hardcoded 8088 in the Splunk tool.

https://github.com/nheijmans/malzoo/blob/a598dabcc36e44f3ec0ab6a4b16924ac7be17c7d/malzoo/core/tools/splunk.py#L12

**Comment by nheijmans** [comment]
Hi @tcwaddell 3acd21d contains the update suggestion!
